baseURL = 'https://emlaver.github.io/gh-pages-example'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'carbon-hugo-theme'
publishDir = 'docs'
canonifyURLs = true
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[menu]
[[menu.header]]
  name = 'Home'
  pageRef = '/'
  weight = 10
[[menu.header]]
  name = 'Search'
  pageRef = '/search.html'
  weight = 20
[[module.mounts]]
   source = 'static'
   target = 'assets'

